services:
  - type: web
    name: ep-linares
    env: dotnet
    plan: free
    branch: deploy/render      # <- reemplaza "main" si tu rama de despliegue es otra
    buildCommand: dotnet publish -c Release
    startCommand: dotnet Ep_Linares.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:${PORT}
      - key: ConnectionStrings__DefaultConnection
        value: "Data Source=portalacademico.db"  
      - key: Redis__ConnectionString
        value: "redis-10808.c246.us-east-1-4.ec2.redns.redis-cloud.com:10808" 
